version: '3.8'

services:
  frontend:
    container_name: frontend
    image: frontend
    build:
      context: ./frontend
    restart: unless-stopped
    ports:
      - 3000:3000
    networks:
      - bidpoint_net

  backend:
    container_name: backend
    image: backend
    build:
      context: ./backend
    restart: unless-stopped
    ports:
      - 8002:8002
    depends_on:
      - db
    networks:
      - bidpoint_net

  db:
    image: 'postgres:14.3-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1234!
    ports:
      - 8001:5432
    restart: unless-stopped
    networks:
      - bidpoint_net

networks:
  bidpoint_net:
    driver: bridge