version: '3.8'

services:
  # frontend:
  #   build:
  #     context: ./frontend
  #   container_name: frontend
  #   ports:
  #     - "3000:80"
  #   restart: unless-stopped
  #   networks:
  #     - bidpoint_net

  # backend:
  #   build:
  #     context: ./backend
  #   container_name: backend
  #   ports:
  #     - 8002:8002
  #   depends_on:
  #     - db
  #   restart: unless-stopped
  #   networks:
  #     - bidpoint_net

  db:
    image: 'postgres:14.3-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1234!
    ports:
      - 8001:5432
    restart: unless-stopped
    networks:
      - bidpoint_net

networks:
  bidpoint_net:
