//Auth
export const SIGNUP_USER_REQUEST = 'SIGNUP_USER_REQUEST';
export const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS';
export const SIGNUP_USER_FAILURE = 'SIGNUP_USER_FAILURE';

export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';

export const LOAD_USER_REQUEST = 'LOAD_USER_REQUEST';
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS';
export const LOAD_USER_FAILURE = 'LOAD_USER_FAILURE';

export const LOGOUT = 'LOGOUT';

//Admin
export const ADMIN_FETCH_ALL_USERS_REQUEST = 'ADMIN_FETCH_ALL_USERS_REQUEST';
export const ADMIN_FETCH_ALL_USERS_SUCCESS = 'ADMIN_FETCH_ALL_USERS_SUCCESS';
export const ADMIN_FETCH_ALL_USERS_FAILURE = 'ADMIN_FETCH_ALL_USERS_FAILURE';

export const ADMIN_APPROVE_USER_REQUEST = 'ADMIN_APPROVE_USER_REQUEST';
export const ADMIN_APPROVE_USER_SUCCESS = 'ADMIN_APPROVE_USER_SUCCESS';
export const ADMIN_APPROVE_USER_FAILURE = 'ADMIN_APPROVE_USER_FAILURE';

//Items
export const GET_ALL_ITEMS_REQUEST = 'GET_ALL_ITEMS_REQUEST';
export const GET_ALL_ITEMS_SUCCESS = 'GET_ALL_ITEMS_SUCCESS';
export const GET_ALL_ITEMS_FAILURE = 'GET_ALL_ITEMS_FAILURE';

export const GET_ITEMS_COUNT_REQUEST = 'GET_ITEMS_COUNT_REQUEST';
export const GET_ITEMS_COUNT_SUCCESS = 'GET_ITEMS_COUNT_SUCCESS';
export const GET_ITEMS_COUNT_FAILURE = 'GET_ITEMS_COUNT_FAILURE';

export const GET_ITEMS_SEARCH_REQUEST = 'GET_ITEMS_SEARCH_REQUEST';
export const GET_ITEMS_SEARCH_SUCCESS = 'GET_ITEMS_SEARCH_SUCCESS';
export const GET_ITEMS_SEARCH_FAILURE = 'GET_ITEMS_SEARCH_FAILURE';
