//Auth
export const SIGNUP_USER_REQUEST = 'SIGNUP_USER_REQUEST';
export const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS';
export const SIGNUP_USER_FAILURE = 'SIGNUP_USER_FAILURE';

export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';

export const LOAD_USER_REQUEST = 'LOAD_USER_REQUEST';
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS';
export const LOAD_USER_FAILURE = 'LOAD_USER_FAILURE';

export const LOGOUT = 'LOGOUT';

//Admin
export const ADMIN_FETCH_ALL_USERS_REQUEST = 'ADMIN_FETCH_ALL_USERS_REQUEST';
export const ADMIN_FETCH_ALL_USERS_SUCCESS = 'ADMIN_FETCH_ALL_USERS_SUCCESS';
export const ADMIN_FETCH_ALL_USERS_FAILURE = 'ADMIN_FETCH_ALL_USERS_FAILURE';

export const ADMIN_APPROVE_USER_REQUEST = 'ADMIN_APPROVE_USER_REQUEST';
export const ADMIN_APPROVE_USER_SUCCESS = 'ADMIN_APPROVE_USER_SUCCESS';
export const ADMIN_APPROVE_USER_FAILURE = 'ADMIN_APPROVE_USER_FAILURE';

export const ADMIN_GET_USER_REQUEST = 'ADMIN_GET_USER_REQUEST';
export const ADMIN_GET_USER_SUCCESS = 'ADMIN_GET_USER_SUCCESS';
export const ADMIN_GET_USER_FAILURE = 'ADMIN_GET_USER_FAILURE';

export const ADMIN_IMPORT_ITEMS_REQUEST = 'ADMIN_IMPORT_ITEMS_REQUEST';
export const ADMIN_IMPORT_ITEMS_SUCCESS = 'ADMIN_IMPORT_ITEMS_SUCCESS';
export const ADMIN_IMPORT_ITEMS_FAILURE = 'ADMIN_IMPORT_ITEMS_FAILURE';

export const ADMIN_EXPORT_ITEMS_REQUEST = 'ADMIN_EXPORT_ITEMS_REQUEST';
export const ADMIN_EXPORT_ITEMS_SUCCESS = 'ADMIN_EXPORT_ITEMS_SUCCESS';
export const ADMIN_EXPORT_ITEMS_FAILURE = 'ADMIN_EXPORT_ITEMS_FAILURE';

//Items
export const GET_ALL_ITEMS_REQUEST = 'GET_ALL_ITEMS_REQUEST';
export const GET_ALL_ITEMS_SUCCESS = 'GET_ALL_ITEMS_SUCCESS';
export const GET_ALL_ITEMS_FAILURE = 'GET_ALL_ITEMS_FAILURE';

export const GET_ITEMS_COUNT_REQUEST = 'GET_ITEMS_COUNT_REQUEST';
export const GET_ITEMS_COUNT_SUCCESS = 'GET_ITEMS_COUNT_SUCCESS';
export const GET_ITEMS_COUNT_FAILURE = 'GET_ITEMS_COUNT_FAILURE';

export const GET_ITEMS_SEARCH_REQUEST = 'GET_ITEMS_SEARCH_REQUEST';
export const GET_ITEMS_SEARCH_SUCCESS = 'GET_ITEMS_SEARCH_SUCCESS';
export const GET_ITEMS_SEARCH_FAILURE = 'GET_ITEMS_SEARCH_FAILURE';

// Item
export const POST_ITEM_REQUEST = 'POST_ITEM_REQUEST';
export const POST_ITEM_SUCCESS = 'POST_ITEM_SUCCESS';
export const POST_ITEM_FAILURE = 'POST_ITEM_FAILURE';

export const GET_ITEM_REQUEST = 'GET_ITEM_REQUEST';
export const GET_ITEM_SUCCESS = 'GET_ITEM_SUCCESS';
export const GET_ITEM_FAILURE = 'GET_ITEM_FAILURE';

export const CREATE_BID_ITEM_REQUEST = 'CREATE_BID_ITEM_REQUEST';
export const CREATE_BID_ITEM_SUCCESS = 'CREATE_BID_ITEM_SUCCESS';
export const CREATE_BID_ITEM_FAILURE = 'CREATE_BID_ITEM_FAILURE';

export const GET_BIDS_ITEM_REQUEST = 'GET_BIDS_ITEM_REQUEST';
export const GET_BIDS_ITEM_SUCCESS = 'GET_BIDS_ITEM_SUCCESS';
export const GET_BIDS_ITEM_FAILURE = 'GET_BIDS_ITEM_FAILURE';

// Categories
export const GET_ALL_CATEGORIES_REQUEST = 'GET_ALL_CATEGORIES_REQUEST';
export const GET_ALL_CATEGORIES_SUCCESS = 'GET_ALL_CATEGORIES_SUCCESS';
export const GET_ALL_CATEGORIES_FAILURE = 'GET_ALL_CATEGORIES_FAILURE';

// Chat
export const GET_ALL_USERS_REQUEST = 'GET_ALL_USERS_REQUEST';
export const GET_ALL_USERS_SUCCESS = 'GET_ALL_USERS_SUCCESS';
export const GET_ALL_USERS_FAILURE = 'GET_ALL_USERS_FAILURE';

export const GET_MESSAGES_REQUEST = 'GET_MESSAGES_REQUEST';
export const GET_MESSAGES_SUCCESS = 'GET_MESSAGES_SUCCESS';
export const GET_MESSAGES_FAILURE = 'GET_MESSAGES_FAILURE';
