spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: jdbc:postgresql://db:5432/postgres
    # url: jdbc:postgresql://localhost:8001/postgres
    username: admin
    password: 1234!
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC
    hibernate:
      ddl-auto: create-drop
  sql:
    init:
      continue-on-error: true
  jackson:
    deserialization:
      ADJUST_DATES_TO_CONTEXT_TIME_ZONE: false
server:
  port: 8002
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:baeldung.p12
    key-alias: baeldung
    key-store-password: password
  error:
    include-message: always
chat:
  port: 8003
  host: localhost