spring:
  datasource:
    url: jdbc:postgresql://localhost:8001/postgres
    username: admin
    password: 1234!
    initialize: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl_auto: update
        format_sql: true
    show-sql: true
server:
  port: 8002
